name: Update BLS Data

on:
  schedule:
    - cron: "0 0 1 * *"  
  workflow_dispatch:  
jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: pip install requests pandas

      - name: Run Data Fetch Script
        run: python fetch_bls_data.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add bls_data.csv last_fetch_date.json
          git commit -m "Automated data update: $(date)"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
